version: '3'

services:
   db:
     image: mariadb:latest
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     ports:
       - 3307
     environment:
       MYSQL_ROOT_PASSWORD: kidbuu976136
       MYSQL_DATABASE: mariadbdatabase
       MYSQL_USER: user
       MYSQL_PASSWORD: user

   wordpress:
     image: phpmyadmin/phpmyadmin:latest
     ports:
       - 81
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3307
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       VIRTUAL_HOST=wpdocker.battlecloud.club

volumes:
db_data:
